StockMaster/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('StockMaster_app.urls')),
    path('admin/', admin.site.urls),
]

StockMaster_app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    
    #paths Login
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('terminos/', views.terminos, name='terminos'),
    path('logout/', views.exit, name='exit'),
    
    #paths Registro
    path('cambio/<str:uidb64>/<str:token>/', views.cambio, name="cambio"),
    path('cambio_password/permiso/<int:id>', views.permiso, name='permiso'),
    path('cambio_password/', views.cambio_password, name='cambio_password'),
    path('recuperar_usuario/eliminaruser/<int:id>', views.eliminaruser, name="eliminaruser"),
    path('usuarios/dar_baja/<int:id>', views.dar_baja, name="dar_baja"),
    path('recuperar_usuario/', views.recuperar_usuario, name="recuperar_usuario"),
    path('recuperar_usuario/recuperar/<int:id>', views.recuperar, name='recuperar'),
    path('cambio_password/descripcion/<int:id_usuario>',views.descripcion, name="descripcion"),

    #paths Productos
    path('productos/', views.pro, name='productos'),
    path('registrarProducto/', views.registrarProducto),
    path('productos/edicioninventario2/<int:idproducts>/', views.edicioninventario2, name='edicioninventario2'),
    path('editarProducto2/', views.editarProductoMod),

    path('productos/status/<int:idproducts>/', views.cambio_status, name='cambio_status'),
    path('statusre/<int:idproducts>/', views.cambio_statusre, name='statusre'),
    path('eliminaInventario/<idproducts>', views.eliminaInventario),
    
    #paths Proveedores
    path('prov/', views.prov, name='prov'),
    path('registrarProv/', views.registrarProv),
    path('prov/edicionProveedor2/<int:idProveedor>', views.edicionProveedor2, name='edicionProveedor2'),
    path('editarProveedor2/', views.editarProveedorMod),

    path('prov/cambio_statuspro/<int:idProveedor>',views.cambio_statuspro, name='cambio_statuspro'),
    path('cambio_statusrepro/<int:idProveedor>', views.cambio_statusrepro, name='cambio_statusrepro'),
    path('eliminaProveedor/<idProveedor>', views.eliminaProveedor),

    #paths Areas
    path('area/', views.area, name='area'),
    path('registraArea/', views.registrar_area),
    path('area/edicionArea2/<int:area_id>', views.edicionArea2, name='edicionArea2'),
    path('editarArea2/', views.editarAreaMod),

    path('status_area/<int:area_id>/',views.status_area,name='status_area'),
    path('status_areare/<int:area_id>/',views.status_areare, name="status_areare"),
    path('eliminar_area/<int:area_id>/', views.eliminar_area, name='eliminar_area'),

    #paths Categorias
    path('config/', views.configuraciones, name='etiquetas'),
    path('registrar_categoria/', views.registrar_categoria, name='registrar_cat'),
    path('config/edicionCategoria2/<int:categoria_id>/', views.edicionCategoria2, name='edicionCategoria2'),
    path('editarCategoria2/', views.editarCategoriaMod),

    path('status_categoria/<int:categoria_id>/',views.status_categoria,name='status_categoria'),
    path('status_categoriare/<int:categoria_id>/',views.status_categoriare, name="status_categoriare"),
    path('eliminar_categoria/<int:categoria_id>/', views.eliminar_categoria, name='eliminarcategoria'),

    #paths Marcas
    path("MarcaVista/",views.MarcaView, name="marca"),
    path("MarcaAgregada/", views.registrar_marca, name="marcaAgred"),
    path('config/edicionMarca2/<int:marca_id>/', views.edicionMarca2, name='edicionMarca2'),
    path('editarMarca2/', views.editarMarcaMod),

    path('cambio_statusremar/<int:marca_id>/', views.cambio_statusremar, name="cambio_statusremar"),
    path('cambio_statusmar/<int:marca_id>/', views.cambio_statusmar, name='cambio_statusmar'),
    path('eliminar-marca/<int:marca_id>/', views.eliminar_marca, name='eliminarmarcas'),

    #paths Roles
    path("rol/",views.RolView, name="rol"),
    path("registrar_rol/", views.registrar_rol, name="registrar_rol"),
    path('rol/edicionRol2/<int:id>/', views.edicionRol2, name='edicionRol2'),
    path('editarRol2/', views.editarRolMod),

    path('cambio_statusrolre/<int:id>/', views.cambio_statusrolre, name="cambio_statusrolre"),
    path('cambio_statusrol/<int:id>/', views.cambio_statusrol, name='cambio_statusrol'),
    path('eliminar_rol/<int:id>/', views.eliminar_rol, name='eliminarRol'),

    #paths comentarios
    path('actividades/eliminarcomentarios/<int:idcomentario>/', views.eliminarcomentarios, name='eliminar_comentario'),
    path('contestarcomentarios/<int:idcomentario>/', views.contestarcomentarios, name='contestarcomentarios'),

    #paths funciones
    path('get_char/', views.get_char, name='get_char'),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    path('editarcant/<int:idproducts>/', views.editarcant, name='editarcant'),

    #paths html
    path('actividades/',views.productos,name='actividades'),
    path('inventario/', views.example_view, name='inventario'),

    path('recuperar_producto', views.recuperar_producto, name='recuperar_producto'),
    path('recuperar_proveedor', views.recuperar_proveedor, name='recuperar_proveedor'),
    path('recuperar_designaciones', views.recuperar_designaciones, name='recuperar_designaciones'),
    path('recuperar_etiquetas', views.recuperar_etiquetas, name='recuperar_etiquetas'),

    path('historial/', views.historial, name='historial'),
    path('historialModificaciones/', views.historialModificaciones, name='historialModificaciones'),
    path('historialMovimientos/', views.historialMovimientos, name='historialMovimientos'),
    path('historialEliminados/', views.historialEliminados, name='historialEliminados'),

    path('soporte/', views.soporte, name='soporte'),
    path('soporteEnviar/', views.soporteEnviar, name='soporteEnviar'),
    path('comentario/',views.comentario),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('acercaDe/', views.acercaDe, name='acercaDe'),
    path('acercaDe/terminos', views.terminosYcondiones, name='terminosCon'),

    path('enviar_correo/', views.enviar_correo, name='enviar_correo'),
    
    #paths de ordenes
    path('ordenes/', views.ordenes, name='ordenes'),
    path('nuevaOrden/', views.nuevaOrden, name='nueva_orden'),
    path('eliminarOrden/<int:id_Orden>/', views.eliminarOrden, name='eliminar_orden')
    ]

StockMaster_app/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.utils import timezone


# Create your models here.
class Categoria(models.Model):
    categoria_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    movi = models.CharField(max_length=255, null=True)
    username = models.CharField(max_length=255, null=True)
    fech_cate = models.DateTimeField(default=timezone.now, null=True)
    status = models.BooleanField(default=True)
    status_mov = models.BooleanField(default=True)
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    marca_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    movi = models.CharField(max_length=100, null= True)
    username = models.CharField(max_length=100, null=True)
    fech_cate= models.DateTimeField(default=timezone.now, null= True)
    status= models.BooleanField(default=True)
    status_mov = models.BooleanField(default=True)
    def __str__(self):
        return self.nombre

class Area(models.Model):
    area_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    movi = models.CharField(max_length=100, null= True)
    username = models.CharField(max_length=100, null=True)
    fech_cate= models.DateTimeField(default=timezone.now, null= True)
    status= models.BooleanField(default=True)
    status_mov = models.BooleanField(default=True)
    def __str__(self):
        return self.nombre


#Modelo de proveedores

class Proveedores(models.Model):    
    idProveedor = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    contacto = models.CharField(max_length=50)
    telefono = models.PositiveBigIntegerField(max_length=10)
    email = models.CharField(max_length=100)
    calle = models.CharField(max_length=100, default="")
    noExt = models.CharField(max_length=50, null=True, default="")
    noInt = models.CharField(max_length=50, null=True, default="")
    colonia = models.CharField(max_length=100, default="")
    cp = models.PositiveBigIntegerField(max_length=5, default="")
    municipio = models.CharField(max_length=100, default="")
    estado = models.CharField(max_length=100, default="")
    pais = models.CharField(max_length=100, default="")
    imagen = models.BinaryField(null=True, blank=True)
    status = models.BooleanField(default=True)
    status_mov = models.BooleanField(default=True)
    hora_baja = models.DateTimeField(default=timezone.now, null=True)
    username = models.CharField(max_length=255, null=True)
    fecha_edit = models.DateTimeField(default=timezone.now, null=True)
    useredit = models.CharField(max_length=255, null=True)
    movimiento = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.nombre


class Productos(models.Model):
    idproducts = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=255)
    nombre = models.CharField(max_length=50)
    precio = models.PositiveBigIntegerField()
    cantPro = models.CharField(max_length=255)
    imagen = models.BinaryField(null=True, blank=True)

    id_categorias = models.ForeignKey(Categoria, on_delete=models.CASCADE, null= True)
    id_Proveedores = models.ForeignKey(Proveedores, on_delete=models.CASCADE, null = True)
    id_marca = models.ForeignKey(Marca, on_delete=models.CASCADE, null= True)
    id_area = models.ForeignKey(Area, on_delete=models.CASCADE, null= True)


    hora_baja = models.DateTimeField(default=timezone.now, null=True)
    username = models.CharField(max_length=255, null=True)
    status = models.BooleanField(default=True)
    fecha_edit = models.DateTimeField(default=timezone.now, null=True)
    useredit = models.CharField(max_length=255, null=True)
    movimiento = models.CharField(max_length=255, null=True)
    status_mov = models.BooleanField(default=True)

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nombre, self.precio)
    
class RolExtra(models.Model):
    grupo = models.OneToOneField(Group, on_delete=models.CASCADE, primary_key=True)
    principal = models.BooleanField(default=False)
    inventario = models.BooleanField(default=False)
    productos = models.BooleanField(default=False)
    proveedores = models.BooleanField(default=False)
    etiquetas = models.BooleanField(default=False)
    area = models.BooleanField(default=False)
    pedidos = models.BooleanField(default=False)
    productosRecuperacion = models.BooleanField(default=False)
    proveedoresRecuperacion = models.BooleanField(default=False)
    etiquetasRecuperacion = models.BooleanField(default=False)
    designadoRecuperacion = models.BooleanField(default=False)
    usuariosRecuperacion = models.BooleanField(default=False)
    usuarios = models.BooleanField(default=False)
    roles = models.BooleanField(default=False)
    soporte = models.BooleanField(default=False)
    soporteenviar = models.BooleanField(default=False)
    contra = models.BooleanField(default=False)
    historialGeneral = models.BooleanField(default=False)
    historialModificaciones = models.BooleanField(default=False)
    historialMovimientos = models.BooleanField(default=False)
    historialEliminados = models.BooleanField(default=False)
    
    movi = models.CharField(max_length=100, null= True)
    username = models.CharField(max_length=100, null=True)
    fech_cate= models.DateTimeField(default=timezone.now, null= True)
    status= models.BooleanField(default=True)
    status_mov = models.BooleanField(default=True)
    def __str__(self):
        return self.nombre

class Mensajes(models.Model):
    idcomentario = models.AutoField(primary_key=True)
    comentario = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    tiempo_creacion = models.DateTimeField(default=timezone.now)
    respuestascomentarios=models.CharField(max_length=255, null=True)
    admincont= models.CharField(max_length=255,null=True)
    tiem_res = models.DateTimeField(default=timezone.now, null=True)
    status = models.BooleanField(default=True)
    status_mov = models.BooleanField(default=True)

    def __str__(self):
        return self.comentario
class Historial(models.Model):
    idhistorial = models.AutoField(primary_key=True)
    movimiento = models.CharField(max_length=255)
    usuario = models.CharField(max_length=255)
    fecha = models.DateTimeField(default=timezone.now, null=True)
    nombre = models.CharField(max_length=255, null=True)

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    mun_cel = models.CharField(max_length=10)
    imagen = models.BinaryField(null=True, blank=True)
    permiso = models.BooleanField(default=True)
    cambio = models.BooleanField(default=True)
    descripcion = models.CharField(max_length=255, null=True)
    comen = models.CharField(max_length =150)
    id = models.ForeignKey(User, on_delete=models.CASCADE, null= True)

        
######################################### Modelo de Ordenes ##############################################################################
class Ordenes(models.Model):
    id_Orden = models.AutoField(primary_key=True)
    no_Orden = models.CharField(max_length=20)
    fechaPedido = models.DateTimeField(default=timezone.now())
    nombreProd = models.CharField(max_length=20)
    codigoProd = models.CharField(max_length=6)
    cantSolicitada = models.IntegerField()
    precioUnitario = models.IntegerField()
    totalPedido = models.IntegerField()
    nombreProv = models.CharField(max_length=50)
    dirProveedor = models.CharField(max_length=100)
    telefonoProv = models.IntegerField()
    emailProv = models.CharField(max_length=100)
    dirEntrega = models.CharField(max_length=100)
    fechaEntrega = models.DateTimeField(null=True)
    metodoPago = models.CharField(max_length=20)
    status = models.CharField(max_length=20)

StockMaster_app/forms.py
from django import forms
from .models import Persona

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['nombre', 'apellido_paterno', 'apellido_materno', 'correo', 'contrasena', 'genero', 'numero_telefono']

StockMaster_app/templates/StockMaster_app/CorreoPedidos.html
<!DOCTYPE html>
<html>
<body>
    <p>
        Estimado/a {{proveedor.nombre}}
    </p>
    <p>
        Espero que este mensaje le encuentre bien. Mi nombre es {{username}} y represento a StockMaster. Estamos interesados en realizar un pedido de los siguientes productos y nos gustaría solicitar su cotización:
    </p>
    <p>
        <b>Detalles del Pedido:</b>
        <br>
        Nombre del Producto: {{producto.nombre}}
        <br>
        Cantidad Solicitada: {{cantPedido}}
        <br>
        Fecha de Entrega Preferida: {{fechaEntrega}}
        <br>
        <br>
        <b>Información de Entrega:</b>
        <br>
        Dirección de Entrega: {{dirEntrega}}
    </p>
    <p>Agradeceríamos que nos proporcionara un presupuesto detallado que incluya el costo de los productos, impuestos, tarifas de envío y cualquier otro cargo relevante. Además, si tiene alguna política específica de pedido mínimo, por favor háganoslo saber.
        <br>
        <br>
        Estamos comprometidos a establecer una relación comercial sólida y a largo plazo. Si tiene algún requisito adicional para procesar nuestra solicitud, no dude en informarnos.
        <br>
        <br>
        Esperamos con interés su pronta respuesta. Gracias por su atención y colaboración.
        <br>
        <br>
        <b>Atte. {{username}}</b>
    </p>
    <a href="{{ accept_link }}" style="background-color: #008CBA; color: #fff; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Activar Cuenta</a>
</body>
</html>

StockMaster_app/templates/StockMaster_app/edicion_categoria.html
{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Título de la Página{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'usuarios/css/agregarProductos.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body {
            background-color: #f4f4f4;
        }

        .row {
            margin-top: 20px;
        }

        .card {
            border: 1px solid #ccc;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .card-body {
            padding: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group input,
        .form-group select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .form-group label {
            font-weight: bold;
        }

        .form-columns {
            display: flex;
            justify-content: space-between;
        }

        .form-column {
            flex: 0 0 48%;
        }

        .update {
            margin-top: 20px;
        }

        .message {
            color: red;
        }

        .error-message {
            color: red;
        }
    </style>
</head>
<body>
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <h2>Edición de Categoria</h2>
            <div class="card">
                <div class="card-body">
                    {% if error_messages %}
                    <div class="alert alert-danger" id="error-alert">
                        <ul>
                            {% for message in error_messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <script>
                        setTimeout(function() {
                            var errorAlert = document.getElementById('error-alert');
                            if (errorAlert) {
                                errorAlert.style.display = 'none';
                            }
                        }, 5000); 
                    </script>
                    {% endif %}
                    <form action="/editarCat/" method="POST" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group py-2">
                            <input type="hidden" name="idCat" value="{{ categoria.categoria_id }}">
                        </div>
                        <div class="form-group py-2">
                            <input type="text" id="txtNombreCat" name="txtNombreCat" value="{{categoria.nombre}}" pattern="[A-Za-z0-9]{6,}" class="form-control" placeholder="Nombre"  minlength="6" maxlength="20" required>
                            <span class="error-message" style="color: red;"></span>
                        </div>                      
                        <div class="form-group py-2">
                            <button type="submit" class="btn btn-success btn-lg btn-block text-white">Guardar</button>
                            <button type="submit" class="btn btn-danger btn-lg btn-block text-white">Cancelar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div> 
        <script>
            const txtNombreCat = document.getElementById("txtNombreCat");

        // Agrega un evento 'input' al campo de texto
        txtNombreCat.addEventListener("input", function () {
            // Convierte el valor del campo de texto en mayúsculas
            this.value = this.value.toUpperCase();
        });

        var campoId = 'txtNombreCat';
        var campo = document.getElementById(campoId);

        campo.addEventListener('input', function () {
            var input = this;
            var errorMessage = input.parentNode.querySelector('.error-message');

            if (input.validity.patternMismatch) {
                errorMessage.textContent = 'El nombre debe contener almenos 6 caracteres alfanuméricos';
            } else {
                errorMessage.textContent = '';
            }
        });
        </script>
    </div>
</body>
</html>
{% endblock %}

StockMaster_app/templates/StockMaster_app/historial.html
{% extends "./base.html" %}
{% block body %}
{% load static %}
<div class="ctn">
    <main>
        <h1>Historial General</h1>
        <div class="recent-orders">
            <div class="principal">
                <div class="encabezado">
                    <h2>Movimientos</h2>
                </div>
                <div class="search-bar-v3">
                    <label for="search-input"></label><input type="text" id="search-input" placeholder="Buscar movimientos..." oninput="convertToUppercase()">
                    <i class="fas fa-search" id="search-icon"></i>
                </div>
            </div>
            <br>
            <div style="overflow: auto; height: 650px;">
                <table>
                    <thead>
                        <tr>
                            <th>Movimiento</th>
                            <th>Nombre</th>
                            <th>Usuario del Movimiento</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for his in historial|dictsortreversed:"fecha" %}
                            <tr>
                                <td align="left">{{ his.movimiento}}</td>
                                <td>{{ his.nombre }}</td>
                                <td>{{ his.usuario}}</td>
                                <td>{{ his.fecha}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    <div class="right" >
        <div class="top">
            <div class="tema">
                <button id="menu-btn"><span class="material-symbols-outlined">menu</span>
                </button>
                <button id="themeToggleBtn" >
                    <i id="sunIcon" class="fas fa-sun"></i>
                    <i id="moonIcon" class="fas fa-moon"></i>
                </button>
            </div>
            <div class="profile">
                {% if request.user.is_authenticated %}
                    <div class="info">
                        <p>Hola, <b>{{ user.username}}</b> </p>
                        <p style="text-align: center;">
                            BIENVENIDO
                        </p>
                    </div>
                    <div class="profile-photo">
                        {% for user in usuarios %}
                                {% if user.id_id == request.user.id %}
                                    {% if user.imagen %}
                                        <img class="fa-solid fa-user-tie"src="{{ user.imagen_url }}" alt="Imagen del usuario">
                                    {% else %}
                                        <p>No hay imagen disponible.</p>
                                    {% endif %}
                                {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="recent-updates">
            <h2>Mensajes Recientes</h2>
            <div class="updates">
                {% if perms.StockMaster_app.view_mensajes %}
                    {% if Mensajes %}
                        {% if respuestascomentarios %}
                            <p>respuestas comentarios </p>
                        {% else %}
                            {% for me in Mensajes|dictsortreversed:"tiempo_creacion"|slice:":4" %}
                                {% if me.respuestascomentarios%}
                                    <div class="message">
                                        <div class="icon" style="color: green">
                                            <span class="material-symbols-outlined">forward</span>
                                        </div>
                                            <p><b>{{ me.username }}: </b><br> {{ me.comentario }}</p>
                                        <small class="text-muted" style="font-size: 11px;">Mensaje contestado</small>
                                    </div>
                                {% else %}
                                    <div class="message">
                                        <div class="icon" style="color: red">
                                            <span class="material-symbols-outlined">mark_email_unread</span>
                                        </div>
                                        <p><b>{{ me.username }}: </b><br> {{ me.comentario }}</p>
                                        <small class="text-muted">{{ me.tiempo_creacion }}</small>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% else %}
                        <p>No hay mensajes disponibles en este momento.</p>
                    {% endif %}
            </div>
            <div class="add-products">
                <div>
                    <span class="material-symbols-outlined">add</span> 
                    <a href="{% url 'soporte' %}">Mostrar Todas</a>
                </div>
            </div>
                {% else %}
                    {% if Mensajes %}
                        {% for me in Mensajes|dictsortreversed:"tiempo_creacion"|slice:":4" %}
                            {% if me.respuestascomentarios %}
                                {% if me.username == request.user.username %}
                                    
                                    <div class="message">
                                        <div class="icon" style="color: green">
                                            <span class="material-symbols-outlined">forward</span>
                                        </div>
                                            <b>Comentario:</b>
                                            <p>{{me.comentario}}</p>
                                            <b>Respuesta del Admin: </b>
                                            <p>{{ me.comentario }}</p>
                                    </div>
                                {% endif %}
                            {% else %}
                                {% if me.username == request.user.username %}
                                    <div class="message">
                                        <div class="icon" style="color: green">
                                            <span class="material-symbols-outlined">forward</span>
                                        </div>
                                            <b>Comentario:</b>
                                            <p>{{me.comentario}}</p>
                                            <b>Respuesta del Admin: </b>
                                            <br>
                                        <small class="text-muted">Sin respuesta</small>
                                    </div> 
                                {% endif %}
                            {% endif%}
                        {% endfor%}
                    {% else %}
                        <p>No tienes ningun comentario por el momento</p>
                    {% endif %}
                </div>
                <div class="add-products">
                    <div>
                        <span class="material-symbols-outlined">add</span> 
                        <a href="{% url 'soporteEnviar' %}">Mostrar Todas</a>
                    </div>
                </div>
                {% endif %}
            

            
            <script>
                // Obtén todos los elementos con la clase "close-btn"
                var closeBtns = document.querySelectorAll('.close-btnn');

                // Agrega un evento de clic a cada elemento
                closeBtns.forEach(function (closeBtn) {
                    closeBtn.addEventListener('click', function () {
                        // Oculta el elemento al hacer clic
                        closeBtn.style.display = 'none';
                    });
                });
            </script>
        </div>
    </div>
</div>
{% endblock %}